# In your forked repo, create a ConfigMap with your message
apiVersion: v1
kind: ConfigMap
metadata:
  name: guestbook-ui-html
data:
  index.html: |
    <html><body><h1>Hello This page proves that argocd has deployed required version-2</h1></body></html>
