apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: my-secret
spec:
  encryptedData:
    key1: AgAdxKHCaDkNbjTUy3iu2Kw+3v4zmsWIEu3dZVRZgkiKKGLncftQjASH28qSXUDWvoLiJNULTULyq8QmkbUglu1E14vS444/DFyl9FUftS4dqfu721NdDBwXdUjNFTpn4YDIdQC0DCRN8DISh0KX4cGC3FmkD/qm2tPnc6bnG/RYtHZBu6YkoaopDu8BrhrzUoyH3J6zdyVZb7MyweUM2twZG3P6aD09xAyrVSBEGB7Pj+qkHK3xG0dwRpw9SEwtOMmD1nYEtPmzXWmAuEFZwAjmTChvmGnVAiVMghZPuBEDJNn0p8vtZd+ys2Sdf5xJM2UKTwFYRp2hV+k5e2e9jkIfoQnYaJfwmFhXfHISUPZVfN+oXVY4Jk9lMMY3RnE0H5va67vI/OXcC90KgFpgEkW6u81l236SqUQZk34/dEX07l4t7j//YDWRcJpPnfubTyi+z+AmjFdLBoG2hmahestGg13puaI9jTAcnZlvI5F7U2EQFlkIv7v6RhG9J8EP/mhuZX2KDgriKTLrxmTZBgzfFp6WWhM12BqS8/WL6fMm0hYUqzNThVJt7GVoCCj6AEF60+Y+eahdi76h+oGFZuvjQPFjHPMpcOlQtK/Xy3w5ZysU+kUCTiHlV1L5v4epLeOxaVRZY+jWRONx91WVlX171oMyRSzaZ+29HuUbZxZBffUmYuOWGzO5wBfnBZf/crYy24r11Yj/T/D8dQ==
    key2: AgCEsAzjtSwBajLwF7H8VAcRWp/Moo3scN1HLr5SdOsArwWhwl7CbwqdxNf2Mf00xPpITpka5xTybqFmZu1XKx0uO8Jpt9fuVd9Tt1NneotVlDD3U4VJIYcnvKL7u4w3dbbe9hvo9zfOrn/k3B8p3az66hWBtU6I4wfREu0Q5IdL+wG3ikUep6zH5h1vBCc5rj+S2W2nsQvnaXnw3xjfCCeEl/Uv4vtthx1C72QfSDfNTHS03S+QMAFvVww8ah/xOHK/qoyNitQgjSxurweOdZk4tZK/HwDUk1d/8uImchA7JuqOG/xvz4vwrqdeGx/dDBwlhIqCzmIkBO5fY4rKzNkPKC1QLE+HDD6Q24m9k2O/gkGvegPyVPjJeRF5V46UxFuGZbqqVnA3tUfpGWkKmQGPP3rFaITueoQMXdxMa24ZzdDUkbPW7BADdaM0zkwuKV2X2gh+DvLuzL5VvcEAS+f/rsTrq6BOIvt1ZOsClKoVWmysHdJOmiQtBim9/sEP5wO4oTnBfD66e/tGhUWkxnm9TjFcTfJP5SHkjV/EzAHsUWmaD8HAPU6lJPQ9MzmGfj6CIJtdapSeJNO9ITfNhUyYt/EXphNj97PJnuX+nLv9+mOWJA7sFf1wkCQbX+6RVBDGgpIMnA6Xi9iBbLHnfooCJBIRyltdnYMHiFDKomIhFHkiDkRNQLxAufr24HM9QAjro0ez5kCDox8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: my-secret
